"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
"""


def findTheDifference(s, t):
    s_dic = {}
    t_dic = {}

    for i in s:
        if i not in s_dic.keys():
            s_dic[i] = 0
        s_dic[i] += 1

    for i in t:
        if i not in t_dic.keys():
            t_dic[i] = 0
        t_dic[i] += 1

    if t_dic.keys() - s_dic.keys():
        tmp = t_dic.keys() - s_dic.keys()
        return list(tmp)[0]
    else:
        for i in t_dic.keys():
            if t_dic[i] != s_dic[i]:
                return i


def solution(s, t):
    sc, tc = 0, 0
    for i in s:
        sc += ord(i)
    for i in t:
        tc += ord(i)
    return chr(tc - sc)


s = 'aabcde'
t = 'aabcdee'
print(solution(s, t))
